project:
  type: website
  output-dir: _site

website:
  title: "FISIOLOGIACLINICA.EU"
  back-to-top-navigation: false
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Início
      - href: sobre/index.qmd
        text: Sobre
      - href: eventos/index.qmd
        text: Eventos
  cookie-consent:
    type: express
    style: headline
    palette: light
  google-analytics:
    tracking-id: "G-MMV2EQNFVD"
    anonymize-ip: true
        
  page-footer:
    left: "2024 fisiologiaclinica.eu" 
    # right: 
    #  - icon: instagram
    #    href: https://github.com/
    #  - icon: twitter 
    #    href: https://twitter.com/ 
format:
  html:
    pagetitle: "{{< meta title >}} | fisiologia clinica . eu"
    theme: journal
    css: styles.css
    # grid:
      # body-width: 800px
    anchor-sections: true
    link-external-icon: false
    link-external-newwindow: true
    footnotes-hover: true
    toc: true
    page-layout: full


    

